title: Roadmap
description: My Roadmap
author: Java Roadmap
github: https://github.com/javaroadmap
about: Go for it ~
disqus_shortname: javaroadmap
google_analytics: UA-135560045-1
avatar_url: /static/img/avatar.jpg
enableTags: true
tagarray: []
collections:
  project:
    output: true
    permalink: /project/:path/
social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/javaroadmap"
share:
  twitter_username: github.io
  fb_appid: github.io
urls:
    - text: 자바로드맵
      url: /about/
    - text: 프로젝트
      url: /projects/
    - text: XML
      url: /feed.xml
url: "https://javaroadmap.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
 
